# Generated by Django 4.1.7 on 2023-03-03 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(max_length=250)),
                ('duration', models.CharField(max_length=50)),
                ('institute', models.CharField(max_length=250)),
                ('address', models.CharField(max_length=250)),
            ],
        ),
    ]
