# Generated by Django 4.1.7 on 2023-03-07 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PortFolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=100)),
                ('project_type', models.CharField(max_length=100)),
                ('client_name', models.CharField(max_length=250)),
                ('project_date', models.DateField()),
                ('project_url', models.URLField()),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='portfolio/images/')),
            ],
        ),
    ]
