# Generated by Django 4.1.7 on 2023-03-07 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='project_type',
            field=models.CharField(choices=[('Web', 'web'), ('app', 'App'), ('logo', 'logo'), ('Social Media', 'Social Media')], max_length=100),
        ),
    ]
