# Generated by Django 4.1.7 on 2023-03-09 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experience', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='from_date',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='experience',
            name='to_date',
            field=models.CharField(max_length=10),
        ),
    ]
