# Generated by Django 4.1.7 on 2023-03-09 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experience', '0002_alter_experience_from_date_alter_experience_to_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='company',
            field=models.CharField(default='Present', max_length=150),
        ),
    ]
