# Generated by Django 4.1.7 on 2023-03-09 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experience', '0004_alter_experience_company_alter_experience_from_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='from_date',
            field=models.IntegerField(choices=[('Present', 1980), ('Present', 1981), ('Present', 1982), ('Present', 1983), ('Present', 1984), ('Present', 1985), ('Present', 1986), ('Present', 1987), ('Present', 1988), ('Present', 1989), ('Present', 1990), ('Present', 1991), ('Present', 1992), ('Present', 1993), ('Present', 1994), ('Present', 1995), ('Present', 1996), ('Present', 1997), ('Present', 1998), ('Present', 1999), ('Present', 2000), ('Present', 2001), ('Present', 2002), ('Present', 2003), ('Present', 2004), ('Present', 2005), ('Present', 2006), ('Present', 2007), ('Present', 2008), ('Present', 2009), ('Present', 2010), ('Present', 2011), ('Present', 2012), ('Present', 2013), ('Present', 2014), ('Present', 2015), ('Present', 2016), ('Present', 2017), ('Present', 2018), ('Present', 2019), ('Present', 2020), ('Present', 2021), ('Present', 2022), ('Present', 2023)], default=2023),
        ),
        migrations.AlterField(
            model_name='experience',
            name='to_date',
            field=models.CharField(choices=[('Present', 1980), ('Present', 1981), ('Present', 1982), ('Present', 1983), ('Present', 1984), ('Present', 1985), ('Present', 1986), ('Present', 1987), ('Present', 1988), ('Present', 1989), ('Present', 1990), ('Present', 1991), ('Present', 1992), ('Present', 1993), ('Present', 1994), ('Present', 1995), ('Present', 1996), ('Present', 1997), ('Present', 1998), ('Present', 1999), ('Present', 2000), ('Present', 2001), ('Present', 2002), ('Present', 2003), ('Present', 2004), ('Present', 2005), ('Present', 2006), ('Present', 2007), ('Present', 2008), ('Present', 2009), ('Present', 2010), ('Present', 2011), ('Present', 2012), ('Present', 2013), ('Present', 2014), ('Present', 2015), ('Present', 2016), ('Present', 2017), ('Present', 2018), ('Present', 2019), ('Present', 2020), ('Present', 2021), ('Present', 2022), ('Present', 2023)], default='Present', max_length=10),
        ),
    ]
