# Generated by Django 4.1.7 on 2023-02-28 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutMe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intro', models.TextField()),
                ('position', models.CharField(max_length=50)),
                ('birthday', models.DateField()),
                ('age', models.IntegerField()),
                ('website', models.CharField(max_length=50)),
                ('degree', models.CharField(max_length=20)),
                ('phone', models.IntegerField()),
                ('email', models.EmailField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('freelance', models.BooleanField()),
                ('short_desc', models.TextField()),
                ('long_desc', models.TextField()),
                ('photo', models.ImageField(upload_to='')),
            ],
        ),
    ]
