# Generated by Django 4.1.7 on 2023-03-08 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_alter_portfolio_project_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='project_type',
            field=models.CharField(choices=[('web', 'Web'), ('app', 'App'), ('logo', 'Logo'), ('social', 'Social Media')], max_length=100),
        ),
    ]
